development: &default
  :frequency: 100 # notify if errors/hour is greater than this
  :subdomain: your-company # airbrake subdomain
  :auth_token: muahahahaha # airbrake auth token from user page (NOT API KEY!)
  :emails: # emails to assign errors to
    - foo@yourcompany.com
  #:ccs: # emails to send as cc
  #  - stalker@yourcompany.com
  :mailer: # mailer config == your gmail credentials
    :username: airman-notifier@yourcompany.com
    :password: your-password
  # :report_errors_to: airbrake-api-key # if any errors happen in airbrake, send them here

test:
  <<: *default

production:
  <<: *default
