development: &default
  :frequency: 100 # notify if errors/hour is greater than this
  :subdomain: your-company # airbrake subdomain
  :auth_token: muahahahaha # airbrake auth token from user page (NOT API KEY!)
  :emails: # emails to send to
    - foo@yourcompany.com
  :mailer: # mailer config aka your gmail credentials
    :username: airman-notifier@yourcompany.com
    :password: your-password

test:
  <<: *default

production:
  <<: *default
